# Generated by Django 6.0.3 on 2026-03-24 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("experiments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending_approval", "待簽核"),
                            ("approved", "已核准"),
                            ("returned", "已退回"),
                            ("rejected", "已拒絕"),
                            ("sample_shipped", "已送樣"),
                            ("in_progress", "處理中"),
                            ("exception", "異常處理中"),
                            ("completed", "已完成"),
                            ("closed", "已結單"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "request",
            },
        ),
        migrations.CreateModel(
            name="ApprovalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "核准"),
                            ("return", "退回"),
                            ("reject", "拒絕"),
                        ],
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_logs",
                        to="commissions.request",
                    ),
                ),
            ],
            options={
                "db_table": "approval_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "experiment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="experiments.experimenttype",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_experiments",
                        to="commissions.request",
                    ),
                ),
            ],
            options={
                "db_table": "request_experiment",
                "unique_together": {("request", "experiment_type")},
            },
        ),
        migrations.AddField(
            model_name="request",
            name="experiment_types",
            field=models.ManyToManyField(
                related_name="requests",
                through="commissions.RequestExperiment",
                to="experiments.experimenttype",
            ),
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wafer_id", models.CharField(max_length=100)),
                (
                    "wafer_size",
                    models.CharField(
                        choices=[("200mm", "200mm"), ("300mm", "300mm")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "已建立"),
                            ("shipped", "已送樣"),
                            ("received", "已接樣"),
                            ("receiving_exception", "接樣異常"),
                            ("split", "已分貨"),
                            ("processing_exception", "處理異常"),
                            ("completed", "已完成"),
                            ("returned", "已退回"),
                            ("voided", "已作廢"),
                        ],
                        default="created",
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="commissions.request",
                    ),
                ),
            ],
            options={
                "db_table": "sample",
            },
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["requester", "status"], name="request_request_9e45fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["status"], name="request_status_10f29f_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["created_at"], name="request_created_b6496a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["request", "status"], name="sample_request_8356ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["status"], name="sample_status_585bcb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="sample",
            unique_together={("request", "wafer_id")},
        ),
    ]
