# Generated by Django 6.0.3 on 2026-03-24 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvallog",
            options={"ordering": ["-created_at", "-pk"]},
        ),
    ]
