# Generated by Django 6.0.3 on 2026-04-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0003_alter_sample_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "已建立"),
                    ("shipped", "已送樣"),
                    ("received", "已接樣"),
                    ("receiving_exception", "接樣異常"),
                    ("processing", "處理中"),
                    ("processing_exception", "處理異常"),
                    ("completed", "已完成"),
                    ("lost", "送樣遺失"),
                    ("returned", "已退回"),
                    ("voided", "已作廢"),
                ],
                default="created",
                max_length=30,
            ),
        ),
    ]
