# Generated by Django 6.0.3 on 2026-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0003_alter_sample_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="urgency",
            field=models.CharField(
                choices=[("3d", "3 days"), ("1w", "1 week"), ("2w", "2 weeks")],
                default="1w",
                max_length=4,
            ),
        ),
    ]
