# Generated by Django 6.0.3 on 2026-05-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0004_request_urgency"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
