# Generated by Django 6.0.3 on 2026-05-20 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0004_alter_sample_status"),
        ("commissions", "0005_sample_received_at"),
    ]

    operations = []
