# Generated by Django 6.0.3 on 2026-03-27 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0003_alter_sample_status"),
        ("equipment", "0001_initial"),
        ("experiments", "0001_initial"),
        ("wip", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待派貨"),
                            ("dispatched", "已派貨"),
                            ("running", "執行中"),
                            ("execution_exception", "執行異常"),
                            ("unloaded", "已下貨"),
                            ("result_recorded", "結果已登錄"),
                            ("completed", "已完成"),
                            ("pending_redispatch", "待重派"),
                            ("aborted", "已中止"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dispatch",
            },
        ),
        migrations.AlterUniqueTogether(
            name="wipsample",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="wipsample",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="wipsample",
            name="wip",
        ),
        migrations.RemoveIndex(
            model_name="wip",
            name="wip_equipme_5b1f7c_idx",
        ),
        migrations.RemoveIndex(
            model_name="wip",
            name="wip_dispatc_ebd961_idx",
        ),
        migrations.RemoveField(
            model_name="experimentresult",
            name="wip",
        ),
        migrations.AddField(
            model_name="wip",
            name="sample",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wip",
                to="commissions.sample",
            ),
        ),
        migrations.AlterField(
            model_name="wip",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "已建立"),
                    ("in_progress", "處理中"),
                    ("completed", "已完成"),
                    ("aborted", "已中止"),
                ],
                default="created",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_dispatches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatches",
                to="equipment.equipment",
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="experiment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatches",
                to="experiments.experimenttype",
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatches",
                to="equipment.recipe",
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="wip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatches",
                to="wip.wip",
            ),
        ),
        migrations.AddField(
            model_name="experimentresult",
            name="dispatch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="wip.dispatch",
            ),
        ),
        migrations.RemoveField(
            model_name="wip",
            name="dispatched_at",
        ),
        migrations.RemoveField(
            model_name="wip",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="wip",
            name="experiment_type",
        ),
        migrations.RemoveField(
            model_name="wip",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="wip",
            name="samples",
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(fields=["status"], name="dispatch_status_b06192_idx"),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["equipment", "status"], name="dispatch_equipme_a6bbd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["wip", "status"], name="dispatch_wip_id_a8457a_idx"
            ),
        ),
        migrations.DeleteModel(
            name="WIPSample",
        ),
    ]
