# Generated by Django 6.0.3 on 2026-03-27 03:06

import django.db.models.deletion
from django.db import migrations, models


def assert_no_null_dispatch(apps, schema_editor):
    # Guard: fail fast if any ExperimentResult has dispatch=NULL before we enforce NOT NULL.
    # On a fresh database this will always pass; on a migrated database it catches orphaned rows.
    ExperimentResult = apps.get_model("wip", "ExperimentResult")
    null_count = ExperimentResult.objects.filter(dispatch__isnull=True).count()
    if null_count:
        raise RuntimeError(
            f"Cannot make ExperimentResult.dispatch non-nullable: "
            f"{null_count} row(s) have dispatch=NULL. Backfill or delete them first."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0003_alter_sample_status"),
        ("wip", "0002_dispatch_alter_wipsample_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(assert_no_null_dispatch, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="experimentresult",
            name="dispatch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="wip.dispatch",
            ),
        ),
        migrations.AlterField(
            model_name="wip",
            name="sample",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wip",
                to="commissions.sample",
            ),
        ),
    ]
