# Generated by Django 6.0.3 on 2026-05-20 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0003_equipment_parameters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="equipment",
        ),
    ]
