"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

from config import observability

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-_1@qswgegj#t^uz(%9o=hzzdjxz!%0!alot*25r4txk6z94zq-",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = (
    os.environ.get("ALLOWED_HOSTS", "").split(",")
    if os.environ.get("ALLOWED_HOSTS")
    else []
)

RAILWAY_PUBLIC_DOMAIN = os.environ.get("RAILWAY_PUBLIC_DOMAIN")
RAILWAY_STATIC_URL = os.environ.get("RAILWAY_STATIC_URL")

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_PUBLIC_DOMAIN}")

if RAILWAY_STATIC_URL:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_STATIC_URL}")

# CORS — DEBUG-only allowlist for the standalone SPA served from a
# separate dev port. Production runs the SPA same-origin via whitenoise,
# so no CORS allowlist is needed there. CLAUDE.local.md hard rule:
# do not enable CORS in production from this branch.
if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:8080",
        "http://127.0.0.1:8080",
    ]
else:
    CORS_ALLOWED_ORIGINS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "ninja",
    "corsheaders",
    "django_prometheus",
    # Local apps
    "apps.accounts",
    "apps.experiments",
    "apps.equipment",
    "apps.commissions",
    "apps.wip",
    "apps.reports",
    "apps.web",
]

LOGIN_URL = "/login/"

# django-prometheus middleware must wrap the entire stack so request
# duration metrics include time spent in other middleware. Before* runs
# first, After* runs last.
_PROMETHEUS_BEFORE = (
    ("django_prometheus.middleware.PrometheusBeforeMiddleware",)
    if observability.metrics_enabled()
    else ()
)
_PROMETHEUS_AFTER = (
    ("django_prometheus.middleware.PrometheusAfterMiddleware",)
    if observability.metrics_enabled()
    else ()
)

MIDDLEWARE = [
    *_PROMETHEUS_BEFORE,
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # corsheaders must precede CommonMiddleware (and run as early as
    # possible) so it can attach Access-Control-* headers and respond
    # to OPTIONS preflights before any view runs.
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "config.middleware.CsrfExemptApiMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    *_PROMETHEUS_AFTER,
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.web.context_processors.linked_accounts",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        **(
            {"conn_max_age": 600, "conn_health_checks": True}
            if os.environ.get("DATABASE_URL")
            else {}
        ),
    )
}

# Optional: wrap the DB engine with django-prometheus to collect query metrics.
# Disabled by default — adds per-query overhead and only pays off when you want
# per-model query counts on the Grafana dashboard.
if observability.db_instrumentation_enabled():
    _DB_ENGINE_MAP = {
        "django.db.backends.postgresql": "django_prometheus.db.backends.postgresql",
        "django.db.backends.sqlite3": "django_prometheus.db.backends.sqlite3",
        "django.db.backends.mysql": "django_prometheus.db.backends.mysql",
    }
    _current_engine = DATABASES["default"].get("ENGINE")
    if _current_engine in _DB_ENGINE_MAP:
        DATABASES["default"]["ENGINE"] = _DB_ENGINE_MAP[_current_engine]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# JWT Configuration
JWT = {
    "SIGNING_KEY": os.environ.get("JWT_SIGNING_KEY", SECRET_KEY),
    "ALGORITHM": "HS256",
    "ACCESS_TOKEN_LIFETIME_MINUTES": int(
        os.environ.get("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", "30")
    ),
    "REFRESH_TOKEN_LIFETIME_DAYS": int(
        os.environ.get("JWT_REFRESH_TOKEN_LIFETIME_DAYS", "7")
    ),
}

# Logging — always log to stdout (Railway captures container logs). Optionally
# push directly to Loki when LOKI_URL is set, for stacks without a stdout
# scraper (Promtail/Alloy).
_LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO")
_LOG_HANDLERS: dict[str, dict] = {
    "console": {
        "class": "logging.StreamHandler",
        "formatter": "verbose",
    },
}
_loki_handler = observability.loki_handler_config()
if _loki_handler is not None:
    _LOG_HANDLERS["loki"] = _loki_handler

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": (
                "{levelname} {asctime} {name} "
                "trace_id={otelTraceID} span_id={otelSpanID} {message}"
            ),
            "style": "{",
            # Defaults keep the formatter safe when OTel LoggingInstrumentor
            # is not active (i.e. OTEL_EXPORTER_OTLP_ENDPOINT is unset).
            "defaults": {"otelTraceID": "0", "otelSpanID": "0"},
        },
    },
    "handlers": _LOG_HANDLERS,
    "root": {
        "handlers": list(_LOG_HANDLERS.keys()),
        "level": _LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": list(_LOG_HANDLERS.keys()),
            "level": _LOG_LEVEL,
            "propagate": False,
        },
    },
}

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}
