# Generated by Django 6.0.3 on 2026-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("fab_user", "廠區使用者"),
                    ("lab_staff", "實驗室人員"),
                    ("lab_manager", "實驗室主管"),
                ],
                default="fab_user",
                max_length=20,
            ),
        ),
    ]
