# Generated by Django 6.0.3 on 2026-03-24 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("commissions", "0002_alter_approvallog_options"),
        ("equipment", "0001_initial"),
        ("experiments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "已建立"),
                            ("pending_dispatch", "待派貨"),
                            ("dispatched", "已派貨"),
                            ("running", "執行中"),
                            ("execution_exception", "執行異常"),
                            ("unloaded", "已下貨"),
                            ("result_recorded", "結果已登錄"),
                            ("completed", "已完成"),
                            ("aborted", "已中止"),
                            ("pending_redispatch", "待重派"),
                        ],
                        default="created",
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_wips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wips",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "experiment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wips",
                        to="experiments.experimenttype",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wips",
                        to="equipment.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "wip",
            },
        ),
        migrations.CreateModel(
            name="ExperimentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                (
                    "verdict",
                    models.CharField(
                        choices=[("pass", "合格"), ("fail", "不合格")], max_length=10
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "data_source",
                    models.CharField(
                        choices=[("manual", "手動登錄"), ("automated", "自動化")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="wip.wip",
                    ),
                ),
            ],
            options={
                "db_table": "experiment_result",
            },
        ),
        migrations.CreateModel(
            name="WIPSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wip_samples",
                        to="commissions.sample",
                    ),
                ),
                (
                    "wip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wip_samples",
                        to="wip.wip",
                    ),
                ),
            ],
            options={
                "db_table": "wip_sample",
                "unique_together": {("wip", "sample")},
            },
        ),
        migrations.AddField(
            model_name="wip",
            name="samples",
            field=models.ManyToManyField(
                related_name="wips", through="wip.WIPSample", to="commissions.sample"
            ),
        ),
        migrations.AddIndex(
            model_name="wip",
            index=models.Index(fields=["status"], name="wip_status_a64ad1_idx"),
        ),
        migrations.AddIndex(
            model_name="wip",
            index=models.Index(
                fields=["equipment", "status"], name="wip_equipme_5b1f7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wip",
            index=models.Index(fields=["dispatched_at"], name="wip_dispatc_ebd961_idx"),
        ),
    ]
