# Generated by Django 6.0.3 on 2026-04-15
# Step 1: Add new models and fields (keep old fields for data migration).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commissions", "0004_alter_sample_status"),
        ("equipment", "0001_initial"),
        ("experiments", "0001_initial"),
        ("wip", "0003_alter_experimentresult_dispatch_alter_wip_sample"),
    ]

    operations = [
        # --- Create new models ---
        migrations.CreateModel(
            name="SampleExperimentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待處理"),
                            ("in_progress", "處理中"),
                            ("completed", "已完成"),
                            ("failed", "不合格"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispatch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sample_experiment_statuses",
                        to="wip.dispatch",
                    ),
                ),
                (
                    "experiment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sample_statuses",
                        to="experiments.experimenttype",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_statuses",
                        to="commissions.sample",
                    ),
                ),
            ],
            options={
                "db_table": "sample_experiment_status",
                "unique_together": {("sample", "experiment_type")},
            },
        ),
        migrations.CreateModel(
            name="WIPSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wip_samples",
                        to="commissions.sample",
                    ),
                ),
                (
                    "wip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wip_samples",
                        to="wip.wip",
                    ),
                ),
            ],
            options={
                "db_table": "wip_sample",
                "unique_together": {("wip", "sample")},
            },
        ),
        # --- Add new fields to WIP (keep old 'sample' field for data migration) ---
        migrations.AddField(
            model_name="wip",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wips",
                to="equipment.equipment",
            ),
        ),
        migrations.AddField(
            model_name="wip",
            name="samples",
            field=models.ManyToManyField(
                related_name="wips",
                through="wip.WIPSample",
                to="commissions.sample",
            ),
        ),
        # --- Add new indexes ---
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["wip", "experiment_type"], name="dispatch_wip_id_6bce22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sampleexperimentstatus",
            index=models.Index(
                fields=["sample", "status"], name="sample_expe_sample__7e3c50_idx"
            ),
        ),
    ]
