# Generated by Django 6.0.3 on 2026-05-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0003_equipment_parameters"),
        ("wip", "0008_backfill_wip_experiment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatch",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatches",
                to="equipment.equipment",
            ),
        ),
    ]
