# Generated by Django 6.0.3 on 2026-05-20 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0003_equipment_parameters"),
        ("experiments", "0001_initial"),
        ("wip", "0010_backfill_dispatch_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatch",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatches",
                to="equipment.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="wip",
            name="experiment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wips",
                to="experiments.experimenttype",
            ),
        ),
    ]
