# Generated by Django 6.0.3 on 2026-05-20 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wip", "0011_tighten_chat_design_fks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wip",
            name="equipment",
        ),
    ]
