# Generated by Django 6.0.3 on 2026-05-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wip", "0012_drop_wip_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatch",
            name="estimated_duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="預估執行時間（分鐘）。Optional — 派工時可填或留空",
                null=True,
            ),
        ),
    ]
