# Generated by Django 6.0.3 on 2026-03-28 12:31

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("commissions", "0003_alter_sample_status"),
        ("wip", "0003_alter_experimentresult_dispatch_alter_wip_sample"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentUtilizationReport",
            fields=[],
            options={
                "verbose_name": "Equipment Utilization Report",
                "verbose_name_plural": "Equipment Utilization Reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wip.dispatch",),
        ),
        migrations.CreateModel(
            name="RequestStatisticsReport",
            fields=[],
            options={
                "verbose_name": "Request Statistics Report",
                "verbose_name_plural": "Request Statistics Reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("commissions.request",),
        ),
    ]
